Added linters and suggested changes made
rbreva/reviewproject pull request #1
Opened 2022-08-22 20:19 UTC by rbreva

2022-08-22 20:54 UTC, rbreva reviewed
# Changes required ♻️
 
Please add readme.md

Submit for a re-review when you're done. 👨🏼‍💻 

Thanks 👍🏼

2022-08-22 20:54 UTC, rbreva commented on index.html
>  <head>
Please you should use a more descriptive title,

2022-08-22 20:54 UTC, rbreva commented on index.html
>                  <option value="2">Projects</option>
I think it is necessary to review the use of classes and ids

2022-08-22 21:10 UTC, Ugboaja-Uchechi requested changes
Hi @rbreva, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Linters are passing ✔️ 
- Good use of GitHub features 👍 

## Required Changes ♻️
- [ ] **Great job using inline comments and detecting issues in the code 👏 . Kindly make sure you explain why a review was given to a student so they can understand it better 🙏**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 15:28 UTC, rbreva reviewed
### Changes required ♻️

Kindly, It is necessary to take into account that the same id should not be used more than once on the same page. 👍🏼

2022-08-24 15:37 UTC, 1GORDON approved these changes
# Status: APPROVED 🟢 

Hi @rbreva ✋

<img src="https://media.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif" width="480" height="270" class="giphy-embed" />

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! :tada: :clap: :clap: :100:

## Optional suggestions

##### _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

##### Cheers and Happy coding!:clap::clap::clap:
##### Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-08-24 15:43 UTC, merged